const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const articles = [
  { title: "Mérida inaugura hub de robótica e inteligencia artificial || Mérida opens robotics and AI hub || Mérida u yáalil robótica yéetel inteligencia artificial", slug: "merida-hub-robotica-ia", content: "**MÉRIDA, Yucatán** — El gobierno estatal inauguró hoy el Centro de Innovación Tecnológica de Yucatán, un complejo de 12,000 metros cuadrados que albergará a más de 40 startups enfocadas en robótica, inteligencia artificial y manufactura avanzada.\n\nEl secretario de Fomento Económico, Ing. Roberto Cisneros, señaló que la inversión supera los 850 millones de pesos y se espera generar 3,200 empleos directos en los próximos tres años. 'Yucatán se posiciona como el Silicon Valley del Sureste mexicano', declaró durante la ceremonia de apertura.\n\nEl hub ya cuenta con compromisos de empresas como Siemens, Honeywell y tres unicornios tecnológicos latinoamericanos que instalarán sus centros de desarrollo regional en las instalaciones. || **MÉRIDA, Yucatán** — The state government today inaugurated the Yucatán Technology Innovation Center, a 12,000-square-meter complex that will house more than 40 startups focused on robotics, artificial intelligence, and advanced manufacturing.\n\nSecretary of Economic Development Roberto Cisneros noted that the investment exceeds 850 million pesos and is expected to generate 3,200 direct jobs over the next three years. 'Yucatán is positioning itself as the Silicon Valley of southeastern Mexico,' he declared at the opening ceremony.\n\nThe hub already has commitments from companies such as Siemens, Honeywell and three Latin American technology unicorns that will install their regional development centers at the facility. || **MÉRIDA, Yucatán** — U kaajal gobiernoil estado tun u páajtal u yáalil Centro de Innovación Tecnológica de Yucatán, jun p'éel nah 12,000 metro cuadrado ku p'áatal 40 startups ichil robótica, inteligencia artificial yéetel manufactura avanzada.", slug: "merida-hub-robotica-ia", state: "Yucatán", category: "Titulares", imageUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80" },
  { title: "Cancún lidera el turismo de lujo en el Caribe mexicano || Cancún leads luxury tourism in the Mexican Caribbean || Cancún u xoot'ol turismo lujo ichil Caribe mexicano", slug: "cancun-turismo-lujo-caribe", content: "**CANCÚN, Quintana Roo** — La Riviera Maya registró un aumento del 34% en reservaciones de hoteles de cinco estrellas durante el primer trimestre de 2026, consolidando a Quintana Roo como el destino turístico premium más solicitado de América Latina.\n\nDatos de la Secretaría de Turismo federal indican que el gasto promedio por turista internacional alcanzó los 2,847 dólares por visita, un récord histórico impulsado por el segmento de turismo experiencial de ultra lujo. Los principales mercados emisores son Estados Unidos (58%), Canadá (17%) y Europa (14%).\n\nEl director del Consejo de Promoción Turística de Quintana Roo, Lic. Andrés Menéndez, adelantó que la inversión hotelera proyectada para 2026-2027 superará los 4.2 mil millones de dólares, con 18 nuevas propiedades de lujo en desarrollo. || **CANCÚN, Quintana Roo** — The Riviera Maya recorded a 34% increase in five-star hotel reservations during the first quarter of 2026, consolidating Quintana Roo as the most sought-after premium tourist destination in Latin America.\n\nData from the federal Secretariat of Tourism indicates that average spending per international tourist reached $2,847 per visit, a historic record driven by the ultra-luxury experiential tourism segment. The main source markets are the United States (58%), Canada (17%) and Europe (14%).\n\nThe director of the Quintana Roo Tourism Promotion Council, Andrés Menéndez, announced that projected hotel investment for 2026-2027 will exceed $4.2 billion, with 18 new luxury properties in development. || **CANCÚN, Quintana Roo** — U Riviera Maya u yilaj jun p'éel aumentoil 34% ichil reservaciones hoteles cinco estrellas ichil primer trimestre 2026, ku kaajal Quintana Roo bey u destino turístico premium más solicitado ichil América Latina.", slug: "cancun-turismo-lujo-caribe", state: "Quintana Roo", category: "Economía", imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80" },
  { title: "Yucatán aprueba nueva ley de energías renovables || Yucatán approves new renewable energy law || Yucatán u aprovación u ley u energías renovables yóok'ol kaab", slug: "yucatan-ley-energias-renovables", content: "**MÉRIDA, Yucatán** — El Congreso del Estado aprobó por unanimidad la Ley de Transición Energética de Yucatán, que establece la meta de alcanzar el 80% de generación eléctrica a través de fuentes renovables para el año 2035, la más ambiciosa de todo el país.\n\nLa legislación incluye incentivos fiscales para empresas que instalen paneles solares, incentivos para la producción de hidrógeno verde y la creación del Fondo Estatal de Energías Limpias con una capitalización inicial de 1,200 millones de pesos. El diputado presidente de la comisión, Dr. Jorge Medina, explicó que la ley también contempla programas de capacitación para 15,000 técnicos especializados en energías renovables.\n\n'Estamos construyendo el futuro energético del Sureste', afirmó la gobernadora durante la sesión solemne de promulgación. Expertos del sector señalan que Yucatán podría convertirse en exportador neto de energía limpia hacia el centro del país antes de 2030. || **MÉRIDA, Yucatán** — The State Congress unanimously approved the Yucatán Energy Transition Law, which sets the goal of reaching 80% electricity generation through renewable sources by 2035, the most ambitious in the entire country.\n\nThe legislation includes tax incentives for companies installing solar panels, incentives for green hydrogen production and the creation of the State Clean Energy Fund with an initial capitalization of 1.2 billion pesos. The legislative committee president Dr. Jorge Medina explained the law also includes training programs for 15,000 technicians specialized in renewable energies.\n\n'We are building the energy future of the Southeast,' the governor stated during the solemn promulgation session. Industry experts suggest Yucatán could become a net exporter of clean energy to central Mexico before 2030. || **MÉRIDA, Yucatán** — U Congreso u Estado u aprobación tuláakal u Ley de Transición Energética de Yucatán, ku kaajal u objetivo 80% generación eléctrica ichil fuentes renovables ti' 2035.", slug: "yucatan-ley-energias-renovables", state: "Yucatán", category: "Política", imageUrl: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=1200&q=80" },
  { title: "Selección mexicana clasifica al Mundial Sub-20 || Mexican national team qualifies for U-20 World Cup || U selección mexicana u clasificación ti' Mundial Sub-20", slug: "seleccion-mexicana-mundial-sub20", content: "**CIUDAD DE MÉXICO** — La selección nacional mexicana de fútbol Sub-20 logró su clasificación al Campeonato Mundial de la categoría tras vencer 3-1 a Honduras en el partido definitivo del Premundial de la Concacaf, celebrado en el Estadio Azteca ante 85,000 aficionados.\n\nEl delantero jalisciense Rodrigo Fierro fue la figura del torneo con 7 goles en 5 partidos, atrayendo el interés de clubes europeos de primera división. 'Este grupo tiene el potencial para llegar lejos en el mundial', declaró el técnico Jaime Lozano en conferencia de prensa posterior al encuentro.\n\nMéxico compartirá grupo en el mundial con Brasil, Francia y Nigeria, en lo que los analistas ya califican como el 'grupo de la muerte' del torneo. La delegación mexicana viajará en junio hacia la sede del torneo, donde buscará romper la maldición del quinto partido. || **MEXICO CITY** — Mexico's U-20 national soccer team secured its place at the category's World Championship after defeating Honduras 3-1 in the decisive Concacaf Pre-World Cup match, held at Estadio Azteca before 85,000 fans.\n\nJalisco-born forward Rodrigo Fierro was the tournament's standout with 7 goals in 5 matches, attracting interest from top European clubs. 'This group has the potential to go far at the world championship,' said coach Jaime Lozano at the post-match press conference.\n\nMexico will share its World Cup group with Brazil, France and Nigeria, which analysts are already calling the tournament's 'group of death.' The Mexican delegation will travel in June to the tournament's host country, where they will seek to break the fifth-game curse. || **CIUDAD DE MÉXICO** — U selección nacional mexicana de fútbol Sub-20 u logración u clasificación ti' Campeonato Mundial ichil u categoría.", slug: "seleccion-mexicana-mundial-sub20", state: "CDMX", category: "Deportes", imageUrl: "https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=1200&q=80" },
  { title: "Festival de las Ánimas revive tradición maya en Campeche || Festival of the Spirits revives Mayan tradition in Campeche || Festival u Pixano'ob ku yáalil u tradición maya ichil Campeche", slug: "festival-animas-tradicion-maya-campeche", content: "**SAN FRANCISCO DE CAMPECHE** — El Festival Internacional de las Ánimas celebró su edición número 25 transformando el centro histórico de Campeche en un escenario vivo de la cosmogonía maya, atrayendo a más de 120,000 visitantes de 34 países durante sus cinco días de duración.\n\nEl evento, declarado Patrimonio Cultural Inmaterial de la Humanidad por la UNESCO en 2024, presentó este año una instalación artística monumental de la artista maya contemporánea Elena Ucan, quien recreó el Xibalba —el inframundo maya— en una experiencia inmersiva de realidad aumentada que fusiona tecnología de punta con iconografía prehispánica. La instalación recibió elogios unánimes de la crítica especializada internacional.\n\nEl impacto económico del festival en la región campechana superó los 890 millones de pesos, consolidando al evento como el motor cultural-turístico más importante del Golfo de México. || **SAN FRANCISCO DE CAMPECHE** — The International Festival of the Spirits celebrated its 25th edition, transforming Campeche's historic center into a living stage of Mayan cosmogony, attracting more than 120,000 visitors from 34 countries during its five-day run.\n\nThe event, declared Intangible Cultural Heritage of Humanity by UNESCO in 2024, featured this year a monumental artistic installation by contemporary Mayan artist Elena Ucan, who recreated Xibalba — the Mayan underworld — in an augmented reality immersive experience that fuses cutting-edge technology with pre-Hispanic iconography. The installation received unanimous praise from international specialized critics.\n\nThe festival's economic impact on the Campeche region exceeded 890 million pesos, consolidating the event as the most important cultural-tourism engine in the Gulf of Mexico. || **SAN FRANCISCO DE CAMPECHE** — U Festival Internacional u Pixano'ob u celebración u 25 edición, ku jóok'ol u centro histórico de Campeche bey jun p'éel escenario vivo ichil u cosmogonía maya.", slug: "festival-animas-tradicion-maya-campeche", state: "Campeche", category: "Cultura", imageUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=1200&q=80" },
  { title: "Jalisco lidera exportaciones de tequila premium al mercado asiático || Jalisco leads premium tequila exports to the Asian market || Jalisco u xuulab u exportaciones tequila premium ti' u mercado asiático", slug: "jalisco-exportaciones-tequila-asia", content: "**GUADALAJARA, Jalisco** — Las exportaciones de tequila premium y ultra-premium de la región de Los Altos de Jalisco registraron un crecimiento del 47% en el primer trimestre de 2026 hacia mercados asiáticos, impulsadas por la creciente clase media china y la penetración del producto en el mercado japonés de lujo.\n\nEl Consejo Regulador del Tequila reportó que el valor promedio de exportación por litro alcanzó los 85 dólares, una cifra histórica que posiciona al destilado mexicano como el espirituoso premium de mayor crecimiento en Asia-Pacífico. Corea del Sur y Singapur emergieron como los mercados de mayor crecimiento relativo, con aumentos del 89% y 73% respectivamente.\n\nEmpresarios del sector adelantaron inversiones por 2,300 millones de pesos para ampliar la capacidad de producción en los próximos 18 meses, incluyendo la construcción de tres nuevas destilerías artesanales con certificación de comercio justo. || **GUADALAJARA, Jalisco** — Premium and ultra-premium tequila exports from the Los Altos de Jalisco region recorded 47% growth in the first quarter of 2026 to Asian markets, driven by China's growing middle class and the product's penetration in Japan's luxury market.\n\nThe Tequila Regulatory Council reported that the average export value per liter reached $85, a historic figure that positions the Mexican distilled spirit as the fastest-growing premium spirit in Asia-Pacific. South Korea and Singapore emerged as the highest relative growth markets, with increases of 89% and 73% respectively.\n\nIndustry executives announced investments of 2.3 billion pesos to expand production capacity over the next 18 months, including the construction of three new artisanal distilleries with fair trade certification. || **GUADALAJARA, Jalisco** — U exportaciones tequila premium yéetel ultra-premium ichil u región Los Altos de Jalisco u yilaj jun p'éel crecimientoil 47% ichil primer trimestre 2026 ti' u mercados asiáticos.", slug: "jalisco-exportaciones-tequila-asia", state: "Jalisco", category: "Economía", imageUrl: "https://images.unsplash.com/photo-1581349485608-9469926a8e5e?auto=format&fit=crop&w=1200&q=80" },
  { title: "Nuevo León apuesta por la manufactura aeroespacial de siguiente generación || Nuevo León bets on next-generation aerospace manufacturing || Nuevo León ku apuesta ti' u manufactura aeroespacial u siguiente generación", slug: "nuevo-leon-manufactura-aeroespacial", content: "**MONTERREY, Nuevo León** — El cluster aeroespacial de Monterrey anunció la llegada de Raytheon Technologies y Safran Group, que invertirán conjuntamente 1,800 millones de dólares para establecer centros de fabricación de componentes para la próxima generación de aeronaves comerciales y de defensa.\n\nLas nuevas instalaciones, que ocuparán 45 hectáreas en el Parque Industrial Aeroespacial de Apodaca, generarán 6,500 empleos directos altamente especializados, con salarios promedio tres veces superiores al salario manufacturero estatal. El director del Cluster Aeroespacial, Dr. Rafael Garza, señaló que esta inversión consolida a Monterrey entre los cinco principales hubs aeroespaciales de América del Norte.\n\nEl gobernador del estado destacó que Nuevo León cuenta actualmente con 300 empresas aeroespaciales activas y produce componentes presentes en más del 60% de los aviones comerciales que sobrevuelan el continente americano. || **MONTERREY, Nuevo León** — The Monterrey aerospace cluster announced the arrival of Raytheon Technologies and Safran Group, which will jointly invest $1.8 billion to establish component manufacturing centers for the next generation of commercial and defense aircraft.\n\nThe new facilities, which will occupy 45 hectares in the Apodaca Aerospace Industrial Park, will generate 6,500 highly specialized direct jobs, with average salaries three times higher than the state manufacturing wage. Aerospace Cluster director Dr. Rafael Garza noted this investment consolidates Monterrey among the top five aerospace hubs in North America.\n\nThe state governor highlighted that Nuevo León currently has 300 active aerospace companies and produces components present in more than 60% of commercial aircraft flying over the Americas. || **MONTERREY, Nuevo León** — U cluster aeroespacial de Monterrey u anuncioil u yáalil Raytheon Technologies yéetel Safran Group, ku inversión conjunta 1,800 millones dólares.", slug: "nuevo-leon-manufactura-aeroespacial", state: "Nuevo León", category: "Local", imageUrl: "https://images.unsplash.com/photo-1517976547714-720226b864c1?auto=format&fit=crop&w=1200&q=80" },
  { title: "México firma acuerdo histórico de libre comercio con la Unión Europea || Mexico signs historic free trade agreement with the European Union || México u firma u acuerdo histórico libre comercio yéetel u Unión Europea", slug: "mexico-acuerdo-comercio-union-europea", content: "**CIUDAD DE MÉXICO** — El gobierno federal mexicano y la Comisión Europea firmaron hoy la versión modernizada del Acuerdo Global México-UE, un tratado de libre comercio que elimina aranceles en más de 97% de los productos agrícolas e industriales intercambiados entre ambas regiones y establece estándares de protección a la inversión sin precedentes en la historia de las relaciones bilaterales.\n\nEl secretario de Economía, Lic. Marina Hernández, calificó el acuerdo como 'el tratado comercial más ambicioso firmado por México en dos décadas', destacando que el capítulo de servicios digitales y propiedad intelectual refleja los estándares más avanzados a nivel global. Se estima que el acuerdo generará un flujo adicional de comercio bilateral de 45,000 millones de euros anuales en su plena implementación.\n\nLos sectores más beneficiados en México serán el automotriz, el agroalimentario, el textil y el de servicios tecnológicos, que verán reducidas sus barreras de acceso al mercado europeo de 450 millones de consumidores. || **MEXICO CITY** — The Mexican federal government and the European Commission today signed the modernized version of the Mexico-EU Global Agreement, a free trade treaty that eliminates tariffs on more than 97% of agricultural and industrial products exchanged between both regions and establishes unprecedented investment protection standards in the history of bilateral relations.\n\nSecretary of Economy Marina Hernández described the agreement as 'the most ambitious trade treaty signed by Mexico in two decades,' highlighting that the digital services and intellectual property chapter reflects the most advanced global standards. The agreement is estimated to generate an additional bilateral trade flow of 45 billion euros annually at full implementation.\n\nThe sectors most benefited in Mexico will be automotive, agrifood, textile and technology services, which will see reduced barriers to access the European market of 450 million consumers. || **CIUDAD DE MÉXICO** — U gobiernoil federal mexicano yéetel u Comisión Europea u firma bejla'e' u versión modernizada ichil u Acuerdo Global México-UE.", slug: "mexico-acuerdo-comercio-union-europea", state: "CDMX", category: "Internacional", imageUrl: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?auto=format&fit=crop&w=1200&q=80" },
];

async function main() {
  console.log('Seeding news articles...');
  for (const article of articles) {
    try {
      await prisma.post.upsert({
        where: { slug: article.slug },
        update: {},
        create: {
          title: article.title,
          slug: article.slug,
          content: article.content,
          imageUrl: article.imageUrl,
          videoUrl: null,
          state: article.state,
          category: article.category,
          published: true,
        },
      });
      console.log('✅ Seeded:', article.slug);
    } catch (e) {
      console.error('❌ Failed:', article.slug, e.message);
    }
  }
  console.log('Done!');
}

main().finally(() => prisma.$disconnect());
